version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule

linters:
  default: all
  disable:
    - wsl # Deprecated
    - exhaustive
    - exhaustruct
    - lll
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - rowserrcheck # SQL related
    - sqlclosecheck # SQL related
    - varnamelen

  settings:
    dupl:
      threshold: 100
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 10
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
            - pkg: github.com/davecgh/go-spew/spew
              desc: not allowed
    govet:
      enable:
        - shadow
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
        - "-QF1001"
    perfsprint:
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: false

  exclusions:
    presets:
      - comments
      - std-error-handling

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
